drop table regimenes_por_hotel;
drop table estados_por_reserva;
drop table reservas_por_habitacion;
drop table reservas_por_cliente;
drop table habitaciones;
drop table clientes;
drop table tipos_de_identificacion;
drop table estados_de_cliente;
drop table items_facturas;
drop table facturas;
drop table estados_de_reservas;
drop table bajas_temporales_por_hotel;
drop table regimenes_por_hotel;
drop table hoteles;
drop table tipos_de_habitacion;
drop table consumible_por_estadia;
drop table consumibles;
drop table estadias;
drop table reservas;
drop table regimenes;
drop table #TemporalClientesMailRepetido
drop table #TemporalClientesPasaporteRepetido
drop table #ReservasConIngreso
drop table #ReservasCorruptasFacturaFutura
drop table #ReservasCorrectas
drop table funcionalidades_por_rol;
drop table roles;
drop table funcionalidades;